import uuid

from sqlalchemy import Column, DateTime, ForeignKey, Integer, Text, func
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import relationship

from app.database.db import Base

try:
    from pgvector.sqlalchemy import Vector
    PGVECTOR_AVAILABLE = True
except ImportError:
    # Graceful fallback if pgvector not installed yet
    from sqlalchemy import JSON as Vector
    PGVECTOR_AVAILABLE = False


class TranscriptEmbedding(Base):
    """
    Stores small text chunks of a transcript alongside their vector embeddings.
    Used by the RAG (Retrieval-Augmented Generation) system to perform semantic
    search across all of a user's transcripts efficiently.

    Each Transcript is split into overlapping chunks of ~300 words. Each chunk
    gets its own row here with a 768-dimensional embedding vector generated by
    Google's text-embedding-004 model.
    """
    __tablename__ = "transcript_embeddings"

    id            = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    transcript_id = Column(UUID(as_uuid=True), ForeignKey("transcripts.id", ondelete="CASCADE"), nullable=False)
    user_id       = Column(UUID(as_uuid=True), ForeignKey("users.id",       ondelete="CASCADE"), nullable=False)
    chunk_index   = Column(Integer, nullable=False)          # Order of chunk within transcript
    chunk_text    = Column(Text, nullable=False)             # The raw paragraph text
    embedding     = Column(Vector(768), nullable=True)       # 768-dim vector (text-embedding-004)
    created_at    = Column(DateTime(timezone=True), server_default=func.now())

    transcript = relationship("Transcript", backref="embeddings")
